# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-02 12:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180902_0357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_encoder',
        ),
        migrations.AlterField(
            model_name='client',
            name='account_number',
            field=models.CharField(default=b'2018024749', max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='meter_serial_number',
            field=models.CharField(default=b'598376142', max_length=30),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 2, 4, 47, 49, 613144)),
        ),
        migrations.AlterField(
            model_name='collection',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 2, 4, 47, 49, 613180)),
        ),
    ]
