# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-02 12:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180902_0448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterrate',
            old_name='range',
            new_name='name',
        ),
        migrations.AddField(
            model_name='waterrate',
            name='end',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='waterrate',
            name='start',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='account_number',
            field=models.CharField(default=b'2018025333', max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='meter_serial_number',
            field=models.CharField(default=b'175932608', max_length=30),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 2, 4, 53, 33, 670035)),
        ),
        migrations.AlterField(
            model_name='collection',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 2, 4, 53, 33, 670075)),
        ),
    ]
