# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-02 12:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180902_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='account_number',
            field=models.CharField(default=b'2018025343', max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='meter_serial_number',
            field=models.CharField(default=b'107294568', max_length=30),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 2, 4, 53, 43, 874824)),
        ),
        migrations.AlterField(
            model_name='collection',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 2, 4, 53, 43, 874862)),
        ),
    ]
