# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-02 13:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180902_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='water_usage',
        ),
        migrations.AddField(
            model_name='collection',
            name='last_read',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='new_read',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='account_number',
            field=models.CharField(default=b'2018022141', max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='meter_serial_number',
            field=models.CharField(default=b'914356280', max_length=30),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 2, 5, 21, 41, 94090)),
        ),
        migrations.AlterField(
            model_name='collection',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 2, 5, 21, 41, 94139)),
        ),
    ]
