# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-04 02:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180902_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='billing_classification_id',
        ),
        migrations.AddField(
            model_name='collection',
            name='water_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.WaterRate'),
        ),
        migrations.AlterField(
            model_name='client',
            name='account_number',
            field=models.CharField(default=b'2018042306', max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='meter_serial_number',
            field=models.CharField(default=b'784195603', max_length=30),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 3, 18, 23, 6, 212607)),
        ),
        migrations.AlterField(
            model_name='collection',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 3, 18, 23, 6, 212644)),
        ),
    ]
