# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-04 02:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180903_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='employee_id',
        ),
        migrations.AlterField(
            model_name='client',
            name='account_number',
            field=models.CharField(default=b'2018042354', max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='meter_serial_number',
            field=models.CharField(default=b'186250374', max_length=30),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 3, 18, 23, 54, 983261)),
        ),
        migrations.AlterField(
            model_name='collection',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 3, 18, 23, 54, 983296)),
        ),
    ]
