# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-09 02:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180903_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='area',
        ),
        migrations.AddField(
            model_name='employee',
            name='BlockArea',
            field=models.ManyToManyField(to='app.BlockArea'),
        ),
        migrations.AlterField(
            model_name='client',
            name='account_number',
            field=models.CharField(default=b'2018092715', max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='meter_serial_number',
            field=models.CharField(default=b'358094761', max_length=30),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 8, 18, 27, 15, 593616)),
        ),
        migrations.AlterField(
            model_name='collection',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 8, 18, 27, 15, 593654)),
        ),
    ]
