# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-09 03:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20180908_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='BlockArea',
            new_name='block_area',
        ),
        migrations.AddField(
            model_name='collection',
            name='employee_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='account_number',
            field=models.CharField(default=b'2018093848', max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='meter_serial_number',
            field=models.CharField(default=b'164095728', max_length=30),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 9, 11, 38, 48, 57000)),
        ),
        migrations.AlterField(
            model_name='collection',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 9, 11, 38, 48, 57000)),
        ),
    ]
