# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-16 01:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20180909_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Collector', 'verbose_name_plural': 'Collectors'},
        ),
        migrations.AlterField(
            model_name='client',
            name='account_number',
            field=models.CharField(default=b'2018162148', max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='meter_serial_number',
            field=models.CharField(default=b'785931264', max_length=30),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 15, 17, 21, 48, 844315)),
        ),
        migrations.AlterField(
            model_name='collection',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 15, 17, 21, 48, 844353)),
        ),
    ]
