# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 17:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20180924_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProxy',
            fields=[
            ],
            options={
                'verbose_name': 'SMS Announcement',
                'proxy': True,
                'indexes': [],
            },
            bases=('app.client',),
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Surveyor', 'verbose_name_plural': 'Surveyors'},
        ),
        migrations.AlterField(
            model_name='client',
            name='account_number',
            field=models.CharField(default=b'2018305732', max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='meter_serial_number',
            field=models.CharField(default=b'243159867', max_length=30),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 1, 1, 57, 32, 805394)),
        ),
        migrations.AlterField(
            model_name='collection',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 1, 1, 57, 32, 805434)),
        ),
    ]
